spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:
  jpa:
    show-sql: true 
    open-in-view: false 
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2: #conseguir ter um console via browser 
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false